[package]
name = "logging-otel"
version = "1.0.0"
description = "Extension for the logging utilities (present in common-cli crate) that enable use of open telemetry."
edition.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true

[features]
default = []
otel = ["raccoon-otel"]

[dependencies]
common-cli = { workspace = true }
raccoon-otel = { workspace = true, optional = true }