[package]
name = "mqtt"
version = "2.3.1"
description = "Tool for quickly post to or read from a MQTT topic."
edition.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
# Internal
cli-signal-monitor = { workspace = true }
common-cli = { workspace = true }
common-utils = { workspace = true }
common-utils-ext = { workspace = true }

# External
anyhow = { workspace = true }
clap = { workspace = true }
rumqttc = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }