[package]
name = "common-utils"
version = "2.0.0"
description = "Common utils that can be used by any tools. Should be kept as dependency-free as possible."
edition.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
anyhow = { workspace = true }
chrono = { workspace = true }

[dev-dependencies]
rstest = { workspace = true }
tempfile = { workspace = true }