[package]
name = "split"
version = "2.0.1"
description = "Tool for splitting large UTF-8 text or CSV files by line count with header preservation, progress feedback, and graceful shutdown."
edition.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
# Internal
cli-signal-monitor = { workspace = true }
common-cli = { workspace = true }
common-utils = { workspace = true }

# External
anyhow = { workspace = true }
chrono = { workspace = true }
clap = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }