[package]
name = "csvn"
version = "2.0.1"
description = "CLI tool that fills missing CSV fields with defaults and outputs a `_normalized` file for consistent, error-free downstream processing."
edition.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
# Internal
cli-signal-monitor = { workspace = true }
common-cli = { workspace = true }
common-utils = { workspace = true }
common-utils-ext = { workspace = true }

# External
anyhow = { workspace = true }
chrono = { workspace = true }
clap = { workspace = true }
csv = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
rstest = { workspace = true }
tempfile = { workspace = true }