[workspace]
resolver = "2"

members = [
    "crates/macros",
    "crates/ai-tools",
    "crates/shared",
    "crates/tools",
    "crates/tool-cat", "crates/tool-csvn", "crates/tool-eventhub-export", "crates/tool-eventhub-read", "crates/tool-get-lines", "crates/tool-guid"]
