[package]
name = "common-cli-env"
version = "1.1.1"
description = "Utils related to loading and managing environment variables into the cli."
edition.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
# External
anyhow = { workspace = true }
dotenvy = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }