[package]
name = "cat"
version = "2.0.0"
description = "Port of the Unix cat command."
edition.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
common-cli = { workspace = true }
common-utils = { workspace = true }
clap = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
rstest = { workspace = true }
tempfile = { workspace = true }