[package]
name = "whisper"
version = "1.0.1"
edition = "2021"
authors = ["Breno RdV"]
description = "Bare-bones, secure, and private P2P chat"
repository = "https://github.com/brenordv/rusted-toolbox"

[dependencies]
shared = { path = "../shared" }
anyhow = "1.0.100"
clap = "4.5.48"
tracing = "0.1.41"
ratatui = "0.29.0"
chrono = "0.4.42"
color-eyre = "0.6.5"
rsa = { version = "0.9.8", features = ["sha2"] }
rand = "0.9.2"
rand06-compat = "0.1.0"
base64 = "0.22.1"
sha256 = "1.6.0"