[package]
name = "whisper"
version = "1.1.0"
edition = "2021"
authors = ["Breno RdV"]
description = "Bare-bones, secure, and private P2P chat"
repository = "https://github.com/brenordv/rusted-toolbox"

[dependencies]
shared = { path = "../shared" }
anyhow = "1.0.103"
clap = "4.6.1"
tracing = "0.1.44"
ratatui = "0.30.2"
rsa = { version = "0.9.10", features = ["sha2"] }
rand = "0.10.2"
rand06-compat = "0.2.0"
base64 = "0.22.1"
sha256 = "1.6.0"