[package]
name = "eh-export"
version = "2.0.0"
description = "EventHub Message Exporter Companion Tool."
edition.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
# Internal
cli-signal-monitor = { workspace = true }
common-cli = { workspace = true }
common-utils = { workspace = true }
shared-eventhub = { workspace = true }

# External
anyhow = { workspace = true }
chrono = { workspace = true }
clap = { workspace = true }
crossterm = { workspace = true }
csv = { workspace = true }
serde_json = { workspace = true }
sled = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }