[package]
name = "imgx"
version = "1.1.0"
description = "Quick way for editing images from the terminal"
edition.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
shared = { workspace = true }
anyhow = { workspace = true }
clap = { workspace = true, features = ["color"] }
tracing = { workspace = true }
indicatif = { workspace = true }
rayon = { workspace = true }
num_cpus = { workspace = true }
image = { workspace = true, features = ["png", "jpeg", "gif", "webp", "tiff", "avif"] }
gif = { workspace = true }
imagequant = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
