[package]
name = "touch"
version = "2.1.0"
description = "Port of the Unix touch command."
edition.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
# Internal
common-cli = { workspace = true }
common-utils = { workspace = true }

# External
anyhow = { workspace = true }
chrono = { workspace = true }
clap = { workspace = true }
filetime = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
