[package]
name = "touch"
version = "1.0.1"
description = "Port of the Unix touch command."
edition.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
shared = { workspace = true }
filetime = { workspace = true }
anyhow = { workspace = true }
clap = { workspace = true }
chrono = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
