[package]
name = "head"
version = "1.1.0"
description = "Port of the Unix head command"
edition.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
# Internal
cli-signal-monitor = { workspace = true }
common-cli = { workspace = true }
common-utils = { workspace = true }
shared-head-tail = { workspace = true }

# External
anyhow = { workspace = true }
clap = { workspace = true }

[dev-dependencies]
rstest = { workspace = true }
tempfile = { workspace = true }
