[package]
name = "distro-cc"
version = "1.0.0"
description = "Translate distro package manager commands between Linux distributions"
edition.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
shared = { workspace = true }
ai-shared = { workspace = true }
ai-macros = { workspace = true }
tokio = { workspace = true }
anyhow = { workspace = true }
clap = { workspace = true }
shell-words = { workspace = true }
