[package]
name = "common-cli"
version = "1.6.0"
description = "Common CLI arg parser and basic logging shared across all tools."
edition.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
# Internal
common-utils = { workspace = true }

# External
anyhow = {workspace = true }
clap = { workspace = true }
tracing-subscriber = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }