[package]
name = "csvn"
version = "1.1.0"
edition = "2021"
authors = ["Breno RdV"]
description = "CLI tool that fills missing CSV fields with defaults and outputs a `_normalized` file for consistent, error-free downstream processing."
repository = "https://github.com/brenordv/rusted-toolbox"

[dependencies]
shared = { path = "../shared" }
string-interner = "0.20.0"
anyhow = "1.0.103"
clap = "4.6.1"
chrono = "0.4.45"
csv = "1.4.0"
tracing = "0.1.44"