[package]
name = "jwt"
version = "1.1.0"
edition = "2021"
authors = ["Breno RdV"]
description = "Decodes JWT tokens and extracts their public claims, headers, and payload information. Optionally copies claims to clipboard."
repository = "https://github.com/brenordv/rusted-toolbox"

[dependencies]
shared = { path = "../shared" }
clap = "4.6.1"
anyhow = "1.0.103"
tracing = "0.1.44"
colored = "3.1.1"
jsonwebtoken = "10.4.0"
serde_json = "1.0.150"
chrono = "0.4.45"
serde = { version = "1.0.228", features = ["derive"] }