[package]
name = "mock"
version = "1.2.0"
edition = "2021"
authors = ["Breno RdV"]
description = "Mock data generator CLI tool."
repository = "https://github.com/brenordv/rusted-toolbox"

[dependencies]
shared = { path = "../shared" }
clap = "4.6.1"
anyhow = "1.0.103"
tracing = "0.1.44"
rand = "0.10.2"
chrono = { version = "0.4.45", features = ["serde"] }
fake = { version = "5.1.0", features = ["derive", "chrono"] }