[package]
name = "pingx"
version = "2.0.2"
description = "Cross platform CLI tool to ping other hosts."
edition.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
# Internal
common-cli = { workspace = true }
common-utils = { workspace = true }
cli-signal-monitor = { workspace = true }

# External
anyhow = { workspace = true }
chrono = { workspace = true }
clap = { workspace = true }
dns-lookup = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
# ICMP/ICMPv6 ping implementation (RFC 792/4443)
surge-ping = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }