[package]
name = "rusted-toolbox"
version = "1.0.0"
edition = "2021"
authors = ["Breno RdV"]
description = "A collection of CLI utilities ported from Go to Rust"


[[bin]]
name = "ai-agent-chat"
path = "src/bin/ai_agent_chat.rs"

[[bin]]
name = "guid"
path = "src/bin/guid.rs"

[[bin]]
name = "touch"
path = "src/bin/touch.rs"

[[bin]]
name = "cat"
path = "src/bin/cat.rs"

[[bin]]
name = "ts"
path = "src/bin/ts.rs"

[[bin]]
name = "csvn"
path = "src/bin/csvn.rs"

[[bin]]
name = "get-lines"
path = "src/bin/get_lines.rs"

[[bin]]
name = "jwt"
path = "src/bin/jwt.rs"

[[bin]]
name = "split"
path = "src/bin/split.rs"

[[bin]]
name = "eh-read"
path = "src/bin/eh_read.rs"

[[bin]]
name = "eh-export"
path = "src/bin/eh_export.rs"

[dependencies]
dotenv = "0.15.0"
clap = { version = "4.4", features = ["derive"] }
tokio = { version = "1.0", features = ["full"] }
uuid = { version = "1.6", features = ["v4"] }
arboard = "3.3"
csv = "1.3"
chrono = { version = "0.4", features = ["serde"] }
anyhow = "1.0"
thiserror = "1.0"
serde = { version = "1.0", features = ["derive"] }
regex = "1.11.1"
futures = "0.3"
async-std = { version = "1.12", features = ["attributes"] }
encoding_rs = "0.8"
num_cpus = "1.16"
filetime = "0.2"
jsonwebtoken = "9.0"
serde_json = "1.0"
colored = "2.0"
base64 = "0.21"
ctrlc = "3.4"
sled = "0.34"
crossterm = "0.27"
indicatif = "0.17"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
fastrand = "2.0"
log = "0.4"
azeventhubs = "0.20"
azure_core = "0.20"
azure_identity = "0.20"
bytes = "1.5"
url = "2.4"
futures-util = "0.3"
async-trait = "0.1.88"
tokio-stream = "0.1.17"
once_cell = "1.21.3"
memmap2="0.9.5"
string-interner="0.19.0"
reqwest = { version = "0.12.22", features = ["json"] }
dialoguer = "0.11.0"

[dev-dependencies]
tempfile = "3.8"
rstest="0.25.0"