[package]
name = "mock-data-utils"
version = "1.1.2"
description = "Mock data generator utils."
edition.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
# External
anyhow = { workspace = true }
chrono = { workspace = true }
fake = { workspace = true }
rand = { workspace = true }

[dev-dependencies]
rstest = { workspace = true }