[package]
name = "ai-shared"
version = "1.0.1"
description = "Where all AI-related shared code lives."
edition.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
shared = { workspace = true }
ai-macros = { workspace = true }
anyhow = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
async-trait = { workspace = true }
reqwest = { workspace = true }
chrono = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
