[package]
name = "ai-macros"
version = "1.0.0"
edition = "2021"
authors = ["Breno RdV"]
description = "AI Macros used by the rusted-toolbox tools"

[dependencies]
quote = "1.0.40"
syn =  { version = "2.0.106", features = ["full"] }
proc-macro2 = "1.0.101"

[lib]
proc-macro = true
