[package]
name = "common-file-utils"
version = "2.3.0"
description = "Common file system utils. Designed for more complex/specialized operations "
edition.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
# External
anyhow = { workspace = true }
tempfile = { workspace = true }
tracing = { workspace = true }
walkdir = { workspace = true }
