[package]
name = "http"
version = "1.1.0"
description = "Lightweight async HTTP server for quickly serving static files with directory browsing, MIME detection, logging, and secure development-focused features."
edition.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
shared = { workspace = true }
tokio = { workspace = true }
clap = { workspace = true }
warp = { workspace = true }
percent-encoding = { workspace = true }
mime_guess = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
