[package]
name = "common-serialization-utils"
version = "1.0.0"
description = "Common utils for serialization/deserialization of objects."
edition.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true


[dependencies]
anyhow = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }