[package]
name = "seal-gui"
version = "1.0.0"
description = "Desktop GUI for seal: key-based file encryption over the age format"
edition.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
# Internal
common-cli = { workspace = true }
common-gui = { workspace = true }
common-utils = { workspace = true }

# External
anyhow = { workspace = true }
clap = { workspace = true }
eframe = { workspace = true }
egui = { workspace = true }
tracing = { workspace = true }
