[package]
name = "lookup"
version = "2.0.0"
description = "Tool to recursively search for text in files"
edition.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
shared = { workspace = true }
clap = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
regex = { workspace = true }
globset = { workspace = true }
walkdir = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
