[package]
name = "lookup"
version = "3.0.0"
description = "Tool to recursively search for text in files"
edition.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
# Internal
common-cli = { workspace = true }
common-file-utils = { workspace = true }
common-utils = { workspace = true }

# External
anyhow = { workspace = true }
clap = { workspace = true }
globset = { workspace = true }
regex = { workspace = true }
tracing = { workspace = true }
walkdir = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }